# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
dev.kikugie.stonecutter.hard_mode=true
# Mod properties
mod.version=1.0.6
mod.group=me.asone
mod.id=boatview360
mod.name=BoatView360

# Global dependencies
deps.fabric_loader=0.18.2

# https://github.com/Fallen-Breath/conditional-mixin
conditionalmixin_version = 0.6.4
