modLoader = "javafml"
loaderVersion = "[31,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/AsOne2020/BoatView360/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "https://github.com/AsOne2020/BoatView360"
authors = "As_One"
description = '''
Removes the 210° view limit in boats, allowing full 360° camera rotation.
'''
logoFile = "icon.png"

[[dependencies."${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"
